const STORAGE_TRADES='tradeJournalData';
const STORAGE_LEARNS='tradeJournalLearns';
const STORAGE_STRATEGY='tradeJournalStrategy';
const MAX_PHOTOS=5;
const MAX_PHOTO_SIZE=4*1024*1024;

let trades=[];
let learns=[];
let strategies=[];
let currentFilter='all';
let searchQuery='';
let deleteTargetId=null;
let deleteType='trade';
let pendingPhotos=[];
let lightboxImages=[];
let lightboxIndex=0;
let learnCurrentFilter='all';
let learnSearchQuery='';
let learnDeleteTargetId=null;
let learnPendingPhotos=[];
let editingStrategyId=null;
let viewTradeId=null;
let viewLearnId=null;
const $=s=>document.querySelector(s);
const $$=s=>document.querySelectorAll(s);
const els={};

function cacheEls(){Object.assign(els,{headerDate:$('#headerDate'),themeToggle:$('#themeToggle'),tradeForm:$('#tradeForm'),editId:$('#editId'),formTitle:$('#formTitle'),formSubtitle:$('#formSubtitle'),submitBtn:$('#submitBtn'),submitBtnText:$('#submitBtnText'),cancelEditBtn:$('#cancelEditBtn'),searchInput:$('#searchInput'),filterChips:$('#filterChips'),tradeTableBody:$('#tradeTableBody'),mobileCards:$('#mobileCards'),emptyState:$('#emptyState'),tableWrap:$('#tableWrap'),statTotal:$('#statTotal'),statWins:$('#statWins'),statLosses:$('#statLosses'),statRate:$('#statRate'),statStreak:$('#statStreak'),breakdownGrid:$('#breakdownGrid'),exportCsvBtn:$('#exportCsvBtn'),exportExcelBtn:$('#exportExcelBtn'),importBtn:$('#importBtn'),importFile:$('#importFile'),clearAllBtn:$('#clearAllBtn'),deleteModal:$('#deleteModal'),cancelDeleteBtn:$('#cancelDeleteBtn'),confirmDeleteBtn:$('#confirmDeleteBtn'),clearModal:$('#clearModal'),cancelClearBtn:$('#cancelClearBtn'),confirmClearBtn:$('#confirmClearBtn'),toastContainer:$('#toastContainer'),photoUploadZone:$('#photoUploadZone'),photoInput:$('#photoInput'),uploadPreview:$('#uploadPreview'),uploadPlaceholder:$('#uploadPlaceholder'),lightboxOverlay:$('#lightboxOverlay'),lightboxImg:$('#lightboxImg'),lightboxClose:$('#lightboxClose'),lightboxPrev:$('#lightboxPrev'),lightboxNext:$('#lightboxNext'),lightboxCounter:$('#lightboxCounter'),fieldDescription:$('#fieldDescription'),strategiesGrid:$('#strategiesGrid'),strategiesEmptyState:$('#strategiesEmptyState'),addStrategyBtn:$('#addStrategyBtn'),strategyModal:$('#strategyModal'),learnForm:$('#learnForm'),learnEditId:$('#learnEditId'),learnFormTitle:$('#learnFormTitle'),learnFormSubtitle:$('#learnFormSubtitle'),learnDate:$('#learnDate'),learnTitle:$('#learnTitle'),learnDescription:$('#learnDescription'),learnRules:$('#learnRules'),learnSubmitBtn:$('#learnSubmitBtn'),learnSubmitBtnText:$('#learnSubmitBtnText'),learnCancelBtn:$('#learnCancelBtn'),learnPhotoZone:$('#learnPhotoZone'),learnPhotoInput:$('#learnPhotoInput'),learnUploadPreview:$('#learnUploadPreview'),learnUploadPlaceholder:$('#learnUploadPlaceholder'),learnCards:$('#learnCards'),learnEmptyState:$('#learnEmptyState'),learnSearchInput:$('#learnSearchInput'),learnFilterChips:$('#learnFilterChips'),exportLearnBtn:$('#exportLearnBtn'),clearLearnBtn:$('#clearLearnBtn'),learnDeleteModal:$('#learnDeleteModal'),cancelLearnDeleteBtn:$('#cancelLearnDeleteBtn'),confirmLearnDeleteBtn:$('#confirmLearnDeleteBtn'),learnClearModal:$('#learnClearModal'),cancelLearnClearBtn:$('#cancelLearnClearBtn'),confirmLearnClearBtn:$('#confirmLearnClearBtn'),tradeViewModal:$('#tradeViewModal'),tradeViewBody:$('#tradeViewBody'),learnViewModal:$('#learnViewModal'),learnViewBody:$('#learnViewBody')})}

function init(){cacheEls();loadTheme();setHeaderDate();loadData();renderAll();renderLearnAll();renderStrategy();bindEvents()}
function setHeaderDate(){var n=new Date();els.headerDate.textContent=n.toLocaleDateString('en-US',{weekday:'short',day:'numeric',month:'short',year:'numeric'})}
function loadTheme(){var s=localStorage.getItem('tradeJournalTheme')||'light';document.documentElement.setAttribute('data-theme',s)}
function toggleTheme(){var c=document.documentElement.getAttribute('data-theme');var n=c==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',n);localStorage.setItem('tradeJournalTheme',n)}

function loadData(){try{var r=localStorage.getItem(STORAGE_TRADES);trades=r?JSON.parse(r):[]}catch(e){trades=[]}try{var r2=localStorage.getItem(STORAGE_LEARNS);learns=r2?JSON.parse(r2):[]}catch(e){learns=[]}try{var r3=localStorage.getItem(STORAGE_STRATEGY);if(r3){var p=JSON.parse(r3);if(Array.isArray(p))strategies=p;else if(typeof p==='object'&&p!==null)strategies=[p];else{strategies=[{id:genId(),title:'My Strategy',content:r3||'',date:new Date().toISOString().split('T')[0],createdAt:Date.now()}];saveStrategies()}}else{strategies=[]}}catch(e){strategies=[]}}
function saveTrades(){localStorage.setItem(STORAGE_TRADES,JSON.stringify(trades))}
function saveLearns(){localStorage.setItem(STORAGE_LEARNS,JSON.stringify(learns))}
function saveStrategies(){localStorage.setItem(STORAGE_STRATEGY,JSON.stringify(strategies))}

function genId(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function fmtDate(d){if(!d)return'';return new Date(d+'T00:00:00').toLocaleDateString('en-US',{day:'numeric',month:'short',year:'numeric'})}
function esc(s){if(!s)return'';var d=document.createElement('div');d.textContent=s;return d.innerHTML}
function showToast(m){var t=document.createElement('div');t.className='toast';t.textContent=m;els.toastContainer.appendChild(t);setTimeout(function(){if(t.parentNode)t.remove()},3200)}

function renderAll(){renderStats();renderBreakdown();renderHistory()}
function renderStats(){var t=trades.length;var w=trades.filter(function(x){return x.result==='Win'}).length;var l=t-w;var r=t===0?0:(w/t)*100;var s=calcStreak();els.statTotal.textContent=t;els.statWins.textContent=w;els.statLosses.textContent=l;els.statRate.textContent=r%1===0?r+'%':r.toFixed(1)+'%';els.statStreak.textContent=s.count===0?'0':s.count+' '+s.type}
function calcStreak(){if(!trades.length)return{type:'',count:0};var s=trades.slice().sort(function(a,b){return new Date(b.date)-new Date(a.date)||b.createdAt-a.createdAt});var f=s[0].result;var c=0;for(var i=0;i<s.length;i++){if(s[i].result===f)c++;else break}return{type:f==='Win'?'Win':'Loss',count:c}}
function renderBreakdown(){var cats=[{label:'Bull',count:0,cls:'blue'},{label:'Bear',count:0,cls:'blue'},{label:'Range',count:0,cls:'blue'},{label:'SSL',count:0,cls:'purple'},{label:'BSL',count:0,cls:'purple'},{label:'Sweep Yes',count:0,cls:'green'},{label:'MSS Yes',count:0,cls:'green'},{label:'Disp Yes',count:0,cls:'green'}];trades.forEach(function(t){if(t.bias==='Bull')cats[0].count++;if(t.bias==='Bear')cats[1].count++;if(t.bias==='Range')cats[2].count++;if(t.liquidity==='SSL')cats[3].count++;if(t.liquidity==='BSL')cats[4].count++;if(t.sweep==='Yes')cats[5].count++;if(t.mss==='Yes')cats[6].count++;if(t.displacement==='Yes')cats[7].count++});var mx=1;cats.forEach(function(c){if(c.count>mx)mx=c.count});els.breakdownGrid.innerHTML=cats.map(function(c){var p=c.count===0?0:(c.count/mx)*100;return '<div class="breakdown-card"><div class="breakdown-label">'+c.label+'</div><div class="breakdown-bar-track"><div class="breakdown-bar-fill '+c.cls+'" style="width:'+p+'%"></div></div><div class="breakdown-count">'+c.count+' trade'+(c.count!==1?'s':'')+'</div></div>'}).join('')}

function getFilteredTrades(){var r=trades.slice();if(currentFilter!=='all')r=r.filter(function(t){return t.bias===currentFilter||t.result===currentFilter||t.liquidity===currentFilter});if(searchQuery.trim()){var q=searchQuery.toLowerCase();r=r.filter(function(t){return Object.keys(t).some(function(k){if(Array.isArray(t[k]))return false;return String(t[k]).toLowerCase().indexOf(q)!==-1})})}r.sort(function(a,b){return new Date(b.date)-new Date(a.date)||b.createdAt-a.createdAt});return r}

function renderHistory(){var f=getFilteredTrades();if(!f.length){els.emptyState.style.display='block';els.tableWrap.style.display='none';els.mobileCards.innerHTML='';return}els.emptyState.style.display='none';els.tableWrap.style.display='block';var tableHtml='';var cardsHtml='';f.forEach(function(t){tableHtml+='<tr data-id="'+t.id+'"><td>'+fmtDate(t.date)+'</td><td><span class="badge badge-'+t.bias.toLowerCase()+'">'+t.bias+'</span></td><td><span class="badge badge-'+t.liquidity.toLowerCase()+'">'+t.liquidity+'</span></td><td><span class="badge badge-'+(t.sweep==='Yes'?'yes':'no')+'">'+t.sweep+'</span></td><td><span class="badge badge-'+(t.mss==='Yes'?'yes':'no')+'">'+t.mss+'</span></td><td><span class="badge badge-'+(t.displacement==='Yes'?'yes':'no')+'">'+t.displacement+'</span></td><td>'+esc(t.entry)+'</td><td>'+esc(t.sl)+'</td><td>'+esc(t.tp)+'</td><td><span class="badge badge-'+t.result.toLowerCase()+'">'+t.result+'</span></td><td><div class="actions-cell"><button class="action-btn view-btn" data-id="'+t.id+'">View</button><button class="action-btn edit-btn" data-id="'+t.id+'">Edit</button><button class="action-btn action-btn-delete del-btn" data-id="'+t.id+'">Delete</button></div></td></tr>';cardsHtml+='<div class="mobile-card"><div class="mobile-card-header"><span class="mobile-card-date">'+fmtDate(t.date)+'</span><div class="mobile-card-actions"><button class="action-btn view-btn" data-id="'+t.id+'">View</button><button class="action-btn edit-btn" data-id="'+t.id+'">Edit</button><button class="action-btn action-btn-delete del-btn" data-id="'+t.id+'">Del</button></div></div><div class="mobile-card-grid"><div class="mobile-card-item"><span class="mobile-card-label">Bias</span><span class="mobile-card-value"><span class="badge badge-'+t.bias.toLowerCase()+'">'+t.bias+'</span></span></div><div class="mobile-card-item"><span class="mobile-card-label">Liquidity</span><span class="mobile-card-value"><span class="badge badge-'+t.liquidity.toLowerCase()+'">'+t.liquidity+'</span></span></div><div class="mobile-card-item"><span class="mobile-card-label">Entry</span><span class="mobile-card-value">'+esc(t.entry)+'</span></div><div class="mobile-card-item"><span class="mobile-card-label">TP</span><span class="mobile-card-value">'+esc(t.tp)+'</span></div><div class="mobile-card-item"><span class="mobile-card-label">Result</span><span class="mobile-card-value"><span class="badge badge-'+t.result.toLowerCase()+'">'+t.result+'</span></span></div><div class="mobile-card-item"><span class="mobile-card-label">SL</span><span class="mobile-card-value">'+esc(t.sl)+'</span></div></div></div>'});els.tradeTableBody.innerHTML=tableHtml;els.mobileCards.innerHTML=cardsHtml}

function viewTrade(id){var t=trades.find(function(x){return x.id===id});if(!t)return;viewTradeId=id;var p=t.photos||[];var html='';html+='<div class="view-row"><span class="view-label">Date</span><span class="view-value">'+fmtDate(t.date)+'</span></div>';html+='<div class="view-row"><span class="view-label">15M Bias</span><span class="view-value"><span class="badge badge-'+t.bias.toLowerCase()+'">'+t.bias+'</span></span></div>';html+='<div class="view-row"><span class="view-label">Liquidity</span><span class="view-value"><span class="badge badge-'+t.liquidity.toLowerCase()+'">'+t.liquidity+'</span></span></div>';html+='<div class="view-row"><span class="view-label">Sweep</span><span class="view-value"><span class="badge badge-'+(t.sweep==='Yes'?'yes':'no')+'">'+t.sweep+'</span></span></div>';html+='<div class="view-row"><span class="view-label">MSS</span><span class="view-value"><span class="badge badge-'+(t.mss==='Yes'?'yes':'no')+'">'+t.mss+'</span></span></div>';html+='<div class="view-row"><span class="view-label">Displacement</span><span class="view-value"><span class="badge badge-'+(t.displacement==='Yes'?'yes':'no')+'">'+t.displacement+'</span></span></div>';html+='<div class="view-row"><span class="view-label">Entry</span><span class="view-value">'+esc(t.entry)+'</span></div>';html+='<div class="view-row"><span class="view-label">Stop Loss</span><span class="view-value">'+esc(t.sl)+'</span></div>';html+='<div class="view-row"><span class="view-label">Take Profit</span><span class="view-value">'+esc(t.tp)+'</span></div>';html+='<div class="view-row"><span class="view-label">Result</span><span class="view-value"><span class="badge badge-'+t.result.toLowerCase()+'">'+t.result+'</span></span></div>';if(t.description){html+='<div class="view-section-title">Notes</div><div class="view-desc">'+esc(t.description)+'</div>'}if(p.length){html+='<div class="view-section-title">Photos</div><div class="view-photos" id="tradeViewPhotos"></div>'}els.tradeViewBody.innerHTML=html;if(p.length){var photosDiv=document.getElementById('tradeViewPhotos');p.forEach(function(src,i){var img=document.createElement('img');img.className='view-photo';img.src=src;img.alt='Photo '+(i+1);img.setAttribute('data-idx',i);img.addEventListener('click',function(){openLightboxArr(p,i)});photosDiv.appendChild(img)})}$('#tradeViewModal').classList.add('active');document.body.style.overflow='hidden'}
function closeTradeView(){$('#tradeViewModal').classList.remove('active');document.body.style.overflow='';viewTradeId=null}
function tradeViewEdit(){if(viewTradeId){closeTradeView();editTrade(viewTradeId)}}

function viewLearn(id){var l=learns.find(function(x){return x.id===id});if(!l)return;viewLearnId=id;var p=l.photos||[];var html='';html+='<div class="view-row"><span class="view-label">Date</span><span class="view-value">'+fmtDate(l.date)+'</span></div>';html+='<div class="view-row"><span class="view-label">Category</span><span class="view-value"><span class="badge badge-'+(l.category||'note').toLowerCase()+'">'+(l.category||'Note')+'</span></span></div>';html+='<div class="view-row"><span class="view-label">Title</span><span class="view-value">'+esc(l.title)+'</span></div>';if(l.description){html+='<div class="view-section-title">Description</div><div class="view-desc">'+esc(l.description)+'</div>'}if(l.rules){html+='<div class="view-section-title">Key Rules / Takeaways</div><div class="view-desc">'+esc(l.rules)+'</div>'}if(p.length){html+='<div class="view-section-title">Photos</div><div class="view-photos" id="learnViewPhotos"></div>'}els.learnViewBody.innerHTML=html;if(p.length){var photosDiv=document.getElementById('learnViewPhotos');p.forEach(function(src,i){var img=document.createElement('img');img.className='view-photo';img.src=src;img.alt='Photo '+(i+1);img.setAttribute('data-idx',i);img.addEventListener('click',function(){openLightboxArr(p,i)});photosDiv.appendChild(img)})}$('#learnViewModal').classList.add('active');document.body.style.overflow='hidden'}
function closeLearnView(){$('#learnViewModal').classList.remove('active');document.body.style.overflow='';viewLearnId=null}
function learnViewEdit(){if(viewLearnId){closeLearnView();editLearn(viewLearnId)}}

function handleFormSubmit(e){e.preventDefault();var fd=getFormData();if(!fd.date||!fd.bias||!fd.liquidity||!fd.sweep||!fd.mss||!fd.displacement||!fd.entry||!fd.sl||!fd.tp||!fd.result){showToast('Please fill in all required fields.');return}var eid=els.editId.value;if(eid){var idx=-1;for(var i=0;i<trades.length;i++){if(trades[i].id===eid){idx=i;break}}if(idx!==-1){var np=pendingPhotos.length?pendingPhotos:(trades[idx].photos||[]);trades[idx]=Object.assign({},trades[idx],fd,{photos:np})}showToast('Trade updated.');cancelEdit()}else{trades.push(Object.assign({id:genId()},fd,{photos:pendingPhotos.slice(),createdAt:Date.now()}));showToast('Trade added.')}saveTrades();resetForm();renderAll()}
function getFormData(){return{date:$('#fieldDate').value,bias:getActiveBtn('bias'),liquidity:getActiveBtn('liquidity'),sweep:getActiveBtn('sweep'),mss:getActiveBtn('mss'),displacement:getActiveBtn('displacement'),entry:$('#fieldEntry').value.trim(),sl:$('#fieldSL').value.trim(),tp:$('#fieldTP').value.trim(),result:getActiveBtn('result'),description:$('#fieldDescription').value.trim()}}
function getActiveBtn(f){var g=document.querySelector('.btn-group[data-field="'+f+'"]');if(!g)return'';var a=g.querySelector('.seg-btn.active');return a?a.getAttribute('data-value'):''}
function setActiveBtn(f,v){var g=document.querySelector('.btn-group[data-field="'+f+'"]');if(!g)return;g.querySelectorAll('.seg-btn').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-value')===v)})}
function resetForm(){els.tradeForm.reset();els.editId.value='';$$('.btn-group[data-field]').forEach(function(g){if(g.getAttribute('data-field')==='learnCategory')return;g.querySelectorAll('.seg-btn').forEach(function(b){b.classList.remove('active')})});els.submitBtnText.textContent='Add Trade';els.cancelEditBtn.style.display='none';els.formTitle.textContent='New Trade';els.formSubtitle.textContent='Record the setup before you forget it.';pendingPhotos=[];renderUploadPreview()}
function cancelEdit(){resetForm()}
function editTrade(id){var t=null;for(var i=0;i<trades.length;i++){if(trades[i].id===id){t=trades[i];break}}if(!t)return;els.editId.value=t.id;$('#fieldDate').value=t.date;$('#fieldEntry').value=t.entry;$('#fieldSL').value=t.sl;$('#fieldTP').value=t.tp;$('#fieldDescription').value=t.description||'';setActiveBtn('bias',t.bias);setActiveBtn('liquidity',t.liquidity);setActiveBtn('sweep',t.sweep);setActiveBtn('mss',t.mss);setActiveBtn('displacement',t.displacement);setActiveBtn('result',t.result);pendingPhotos=t.photos?t.photos.slice():[];renderUploadPreview();els.submitBtnText.textContent='Update Trade';els.cancelEditBtn.style.display='inline-flex';els.formTitle.textContent='Editing Trade';els.formSubtitle.textContent='Update the details below.';$('#newTradeCard').scrollIntoView({behavior:'smooth',block:'start'})}
function promptDelete(id){deleteTargetId=id;deleteType='trade';els.deleteModal.classList.add('active')}
function confirmDelete(){if(!deleteTargetId)return;if(deleteType==='trade'){trades=trades.filter(function(t){return t.id!==deleteTargetId})}else{learns=learns.filter(function(l){return l.id!==deleteTargetId})}saveTrades();saveLearns();renderAll();renderLearnAll();closeModals();showToast('Deleted.')}
function closeModals(){$$('.modal-overlay').forEach(function(m){m.classList.remove('active')});deleteTargetId=null;learnDeleteTargetId=null}
function promptClearAll(){if(!trades.length){showToast('No trades to clear.');return}els.clearModal.classList.add('active')}
function confirmClearAll(){trades=[];saveTrades();renderAll();closeModals();showToast('All trades cleared.')}

function handlePhotoClick(){els.photoInput.click()}
function handlePhotoFiles(files){var rem=MAX_PHOTOS-pendingPhotos.length;if(rem<=0){showToast('Maximum '+MAX_PHOTOS+' photos allowed.');return}var toProc=Array.from(files).slice(0,rem);var done=0;toProc.forEach(function(f){if(!f.type.startsWith('image/')){done++;if(done===toProc.length)renderUploadPreview();return}if(f.size>MAX_PHOTO_SIZE){done++;if(done===toProc.length)renderUploadPreview();return}var r=new FileReader();r.onload=function(ev){compressImg(ev.target.result,800,.8,function(c){pendingPhotos.push(c);done++;if(done===toProc.length)renderUploadPreview()})};r.readAsDataURL(f)})}
function compressImg(dUrl,maxDim,q,cb){var img=new Image();img.onload=function(){var w=img.width,h=img.height;if(w>maxDim||h>maxDim){if(w>h){h=Math.round(h*maxDim/w);w=maxDim}else{w=Math.round(w*maxDim/h);h=maxDim}}var cv=document.createElement('canvas');cv.width=w;cv.height=h;cv.getContext('2d').drawImage(img,0,0,w,h);cb(cv.toDataURL('image/jpeg',q))};img.src=dUrl}
function removePendingPhoto(i){pendingPhotos.splice(i,1);renderUploadPreview()}
function renderUploadPreview(){els.uploadPreview.innerHTML='';if(pendingPhotos.length){els.uploadPreview.classList.add('has-items');els.uploadPlaceholder.style.display='none';pendingPhotos.forEach(function(s,i){var d=document.createElement('div');d.className=els.editId.value?'preview-existing':'preview-thumb';var img=document.createElement('img');img.src=s;img.alt='Photo '+(i+1);var btn=document.createElement('button');btn.className='preview-remove';btn.innerHTML='&times;';btn.title='Remove';btn.addEventListener('click',function(e){e.stopPropagation();removePendingPhoto(i)});d.appendChild(img);d.appendChild(btn);d.addEventListener('click',function(e){if(e.target===btn||e.target.classList.contains('preview-remove'))return;openLightboxArr(pendingPhotos,i)});els.uploadPreview.appendChild(d)})}else{els.uploadPreview.classList.remove('has-items');els.uploadPlaceholder.style.display=''}}
function handleDragOver(e){e.preventDefault();e.stopPropagation();els.photoUploadZone.classList.add('drag-over')}
function handleDragLeave(e){e.preventDefault();e.stopPropagation();els.photoUploadZone.classList.remove('drag-over')}
function handleDrop(e){e.preventDefault();e.stopPropagation();els.photoUploadZone.classList.remove('drag-over');if(e.dataTransfer.files.length)handlePhotoFiles(e.dataTransfer.files)}
function openLightboxArr(imgs,idx){lightboxImages=imgs;lightboxIndex=idx;updateLightbox();els.lightboxOverlay.classList.add('active');document.body.style.overflow='hidden'}
function updateLightbox(){if(!lightboxImages.length)return;els.lightboxImg.src=lightboxImages[lightboxIndex];els.lightboxCounter.textContent=(lightboxIndex+1)+' / '+lightboxImages.length;els.lightboxPrev.style.display=lightboxImages.length>1?'':'none';els.lightboxNext.style.display=lightboxImages.length>1?'':'none'}
function closeLightbox(){els.lightboxOverlay.classList.remove('active');document.body.style.overflow=''}
function lbPrev(){lightboxIndex=(lightboxIndex-1+lightboxImages.length)%lightboxImages.length;updateLightbox()}
function lbNext(){lightboxIndex=(lightboxIndex+1)%lightboxImages.length;updateLightbox()}

function exportCSV(){if(!trades.length){showToast('No trades to export.');return}var h=['Date','15m Bias','Liquidity','Sweep','MSS','Displacement','Entry','SL','TP','Result','Description'];var rows=trades.sort(function(a,b){return new Date(b.date)-new Date(a.date)}).map(function(t){return[t.date,t.bias,t.liquidity,t.sweep,t.mss,t.displacement,t.entry,t.sl,t.tp,t.result,t.description||'']});var csv=[h].concat(rows).map(function(r){return r.map(function(c){return csvEsc(c)}).join(',')}).join('\n');dlFile(csv,'trade-journal.csv','text/csv;charset=utf-8;');showToast('CSV exported.')}
function csvEsc(v){var s=String(v);return(s.indexOf(',')!==-1||s.indexOf('"')!==-1||s.indexOf('\n')!==-1)?'"'+s.replace(/"/g,'""')+'"':s}
function exportExcel(){if(!trades.length){showToast('No trades to export.');return}var h=['Date','15m Bias','Liquidity','Sweep','MSS','Displacement','Entry','SL','TP','Result','Description'];var html='<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="UTF-8"></head><body><table border="1"><tr>';h.forEach(function(x){html+='<th style="background:#C5ADC5;font-weight:bold;">'+x+'</th>'});html+='</tr>';trades.sort(function(a,b){return new Date(b.date)-new Date(a.date)}).forEach(function(t){var r=[t.date,t.bias,t.liquidity,t.sweep,t.mss,t.displacement,t.entry,t.sl,t.tp,t.result,t.description||''];html+='<tr>';r.forEach(function(c){html+='<td>'+esc(c)+'</td>'});html+='</tr>'});html+='</table></body></html>';var b=new Blob([html],{type:'application/vnd.ms-excel'});var u=URL.createObjectURL(b);var a=document.createElement('a');a.href=u;a.download='trade-journal.xls';document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(u);showToast('Excel exported.')}
function importData(){els.importFile.click()}
function handleImport(e){var f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(ev){var lines=parseCSV(ev.target.result);if(lines.length<2){showToast('No valid trades found.');return}var hdr=lines[0].map(function(h){return h.trim().toLowerCase()});var exp=['date','15m bias','liquidity','sweep','mss','displacement','entry','sl','tp','result','description'];var cm={};exp.forEach(function(eh,i){var idx=-1;for(var j=0;j<hdr.length;j++){if(hdr[j]===eh||hdr[j].replace(/\s+/g,'')===eh.replace(/\s+/g,'')){idx=j;break}}if(idx!==-1)cm[i]=idx});if(Object.keys(cm).length<5){showToast('Could not parse CSV headers.');return}var imp=0;for(var i=1;i<lines.length;i++){var row=lines[i];if(row.length<5)continue;var g=function(c){var m=cm[c];return m!==undefined?(row[m]||'').trim():''};trades.push({id:genId(),date:g(0)||new Date().toISOString().split('T')[0],bias:g(1)||'Range',liquidity:g(2)||'SSL',sweep:g(3)||'No',mss:g(4)||'No',displacement:g(5)||'No',entry:g(6)||'',sl:g(7)||'',tp:g(8)||'',result:g(9)||'Win',description:g(10)||'',photos:[],createdAt:Date.now()+i});imp++}saveTrades();renderAll();showToast('Imported '+imp+' trade'+(imp!==1?'s':'')+'.')};r.readAsText(f);e.target.value=''}
function parseCSV(t){var lines=[];var cur=[];var cell='';var iq=false;for(var i=0;i<t.length;i++){var ch=t[i];var nx=t[i+1];if(iq){if(ch==='"'&&nx==='"'){cell+='"';i++}else if(ch==='"')iq=false;else cell+=ch}else{if(ch==='"')iq=true;else if(ch===','){cur.push(cell);cell=''}else if(ch==='\n'||(ch==='\r'&&nx==='\n')){cur.push(cell);cell='';if(cur.length)lines.push(cur);cur=[];if(ch==='\r')i++}else if(ch==='\r'){cur.push(cell);cell='';if(cur.length)lines.push(cur);cur=[]}else cell+=ch}}if(cell||cur.length){cur.push(cell);lines.push(cur)}return lines}

function renderStrategy(){var g=$('#strategiesGrid');var e=$('#strategiesEmptyState');if(!strategies.length){g.innerHTML='';e.style.display='';return}e.style.display='none';g.innerHTML=strategies.map(function(s){var prev=(s.content||'').substring(0,120).replace(/\n/g,' ');return '<div class="strategy-card" data-id="'+s.id+'"><div class="strategy-card-title">'+esc(s.title)+'</div><div class="strategy-card-preview">'+(prev||'No content yet...')+'</div><div class="strategy-card-meta"><span>'+fmtDate(s.date)+'</span><div class="strategy-card-actions"><button class="action-btn strat-edit-btn" data-id="'+s.id+'">Edit</button><button class="action-btn action-btn-delete strat-del-btn" data-id="'+s.id+'">Delete</button></div></div></div>'}).join('')}
function addNewStrategy(){editingStrategyId=null;$('#strategyModalTitle').value='';$('#strategyModalTextarea').value='';$('#strategyModalDate').textContent=new Date().toLocaleDateString('en-US',{day:'numeric',month:'short',year:'numeric'});$('#deleteStrategyModalBtn').style.display='none';$('#strategyModal').classList.add('active');document.body.style.overflow='hidden';$('#strategyModalTitle').focus()}
function openStrategyModal(id){var s=null;for(var i=0;i<strategies.length;i++){if(strategies[i].id===id){s=strategies[i];break}}if(!s)return;editingStrategyId=id;$('#strategyModalTitle').value=s.title;$('#strategyModalTextarea').value=s.content||'';$('#strategyModalDate').textContent='Created '+fmtDate(s.date);$('#deleteStrategyModalBtn').style.display='';$('#strategyModal').classList.add('active');document.body.style.overflow='hidden';$('#strategyModalTitle').focus()}
function closeStrategyModal(){$('#strategyModal').classList.remove('active');document.body.style.overflow='';editingStrategyId=null}
function saveStrategyModal(){var title=$('#strategyModalTitle').value.trim()||'Untitled Strategy';var content=$('#strategyModalTextarea').value;var isEdit=!!editingStrategyId;if(editingStrategyId){for(var i=0;i<strategies.length;i++){if(strategies[i].id===editingStrategyId){strategies[i].title=title;strategies[i].content=content;break}}}else{strategies.push({id:genId(),title:title,content:content,date:new Date().toISOString().split('T')[0],createdAt:Date.now()})}saveStrategies();renderStrategy();closeStrategyModal();showToast(isEdit?'Strategy updated.':'Strategy added.')}
function promptDeleteStrategy(id){editingStrategyId=id;$('#deleteStrategyModalBtn').style.display=''}
function confirmDeleteStrategy(){if(!editingStrategyId)return;strategies=strategies.filter(function(s){return s.id!==editingStrategyId});saveStrategies();renderStrategy();closeStrategyModal();showToast('Strategy deleted.');editingStrategyId=null}

function renderLearnAll(){renderLearnCards()}
function renderLearnCards(){var f=getFilteredLearns();if(!f.length){els.learnEmptyState.style.display='block';els.learnCards.innerHTML='';return}els.learnEmptyState.style.display='none';els.learnCards.innerHTML=f.map(function(l){var cat=l.category||'Note';var catCls='badge-'+cat.toLowerCase();return '<div class="learn-card"><div class="learn-card-header"><div class="learn-card-meta"><span class="badge '+catCls+'">'+cat+'</span><span class="learn-card-date">'+fmtDate(l.date)+'</span></div></div><div class="learn-card-title">'+esc(l.title)+'</div>'+(l.description?'<div class="learn-card-desc">'+esc(l.description).substring(0,100)+(l.description.length>100?'...':'')+'</div>':'')+'<div class="learn-card-actions"><button class="action-btn learn-view-btn" data-id="'+l.id+'">View</button><button class="action-btn learn-edit-btn" data-id="'+l.id+'">Edit</button><button class="action-btn action-btn-delete learn-del-btn" data-id="'+l.id+'">Delete</button></div></div>'}).join('')}
function getFilteredLearns(){var r=learns.slice();if(learnCurrentFilter!=='all')r=r.filter(function(l){return l.category===learnCurrentFilter});if(learnSearchQuery.trim()){var q=learnSearchQuery.toLowerCase();r=r.filter(function(l){return Object.keys(l).some(function(k){if(Array.isArray(l[k]))return false;return String(l[k]).toLowerCase().indexOf(q)!==-1})})}r.sort(function(a,b){return new Date(b.date)-new Date(a.date)||b.createdAt-a.createdAt});return r}
function handleLearnSubmit(e){e.preventDefault();var fd={date:$('#learnDate').value,category:getActiveBtn('learnCategory'),title:$('#learnTitle').value.trim(),description:$('#learnDescription').value.trim(),rules:$('#learnRules').value.trim(),photos:learnPendingPhotos.slice()};if(!fd.date||!fd.category||!fd.title){showToast('Please fill in date, category, and title.');return}var eid=els.learnEditId.value;if(eid){var idx=-1;for(var i=0;i<learns.length;i++){if(learns[i].id===eid){idx=i;break}}if(idx!==-1){fd.photos=learnPendingPhotos.length?learnPendingPhotos:(learns[idx].photos||[]);learns[idx]=Object.assign({},learns[idx],fd)}showToast('Learning updated.');cancelLearnEdit()}else{fd.id=genId();fd.createdAt=Date.now();learns.push(fd);showToast('Learning saved.')}saveLearns();resetLearnForm();renderLearnAll()}
function editLearn(id){var l=null;for(var i=0;i<learns.length;i++){if(learns[i].id===id){l=learns[i];break}}if(!l)return;els.learnEditId.value=l.id;$('#learnDate').value=l.date;$('#learnTitle').value=l.title;$('#learnDescription').value=l.description||'';$('#learnRules').value=l.rules||'';setActiveBtn('learnCategory',l.category);learnPendingPhotos=l.photos?l.photos.slice():[];renderLearnUploadPreview();els.learnSubmitBtnText.textContent='Update Learning';els.learnCancelBtn.style.display='inline-flex';els.learnFormTitle.textContent='Editing Learning';els.learnFormSubtitle.textContent='Update the details below.';$('#learnFormCard').scrollIntoView({behavior:'smooth',block:'start'})}
function cancelLearnEdit(){resetLearnForm()}
function resetLearnForm(){els.learnForm.reset();els.learnEditId.value='';$$('#tabLearn .btn-group').forEach(function(g){g.querySelectorAll('.seg-btn').forEach(function(b){b.classList.remove('active')})});els.learnSubmitBtnText.textContent='Save Learning';els.learnCancelBtn.style.display='none';els.learnFormTitle.textContent='New Learning';els.learnFormSubtitle.textContent='Save chart patterns, concepts, and insights.';learnPendingPhotos=[];renderLearnUploadPreview()}
function promptLearnDelete(id){learnDeleteTargetId=id;els.learnDeleteModal.classList.add('active')}
function confirmLearnDelete(){if(!learnDeleteTargetId)return;learns=learns.filter(function(l){return l.id!==learnDeleteTargetId});saveLearns();renderLearnAll();closeModals();showToast('Learning deleted.');learnDeleteTargetId=null}
function promptClearLearn(){if(!learns.length){showToast('No learnings to clear.');return}els.learnClearModal.classList.add('active')}
function confirmClearLearn(){learns=[];saveLearns();renderLearnAll();closeModals();showToast('All learnings cleared.')}
function handleLearnPhotoClick(){els.learnPhotoInput.click()}
function handleLearnPhotoFiles(files){var rem=MAX_PHOTOS-learnPendingPhotos.length;if(rem<=0){showToast('Maximum '+MAX_PHOTOS+' photos allowed.');return}var toProc=Array.from(files).slice(0,rem);var done=0;toProc.forEach(function(f){if(!f.type.startsWith('image/')){done++;if(done===toProc.length)renderLearnUploadPreview();return}if(f.size>MAX_PHOTO_SIZE){done++;if(done===toProc.length)renderLearnUploadPreview();return}var r=new FileReader();r.onload=function(ev){compressImg(ev.target.result,800,.8,function(c){learnPendingPhotos.push(c);done++;if(done===toProc.length)renderLearnUploadPreview()})};r.readAsDataURL(f)})}
function removeLearnPendingPhoto(i){learnPendingPhotos.splice(i,1);renderLearnUploadPreview()}
function renderLearnUploadPreview(){els.learnUploadPreview.innerHTML='';if(learnPendingPhotos.length){els.learnUploadPreview.classList.add('has-items');els.learnUploadPlaceholder.style.display='none';learnPendingPhotos.forEach(function(s,i){var d=document.createElement('div');d.className=els.learnEditId.value?'preview-existing':'preview-thumb';var img=document.createElement('img');img.src=s;img.alt='Photo '+(i+1);var btn=document.createElement('button');btn.className='preview-remove';btn.innerHTML='&times;';btn.title='Remove';btn.addEventListener('click',function(e){e.stopPropagation();removeLearnPendingPhoto(i)});d.appendChild(img);d.appendChild(btn);d.addEventListener('click',function(e){if(e.target===btn||e.target.classList.contains('preview-remove'))return;openLightboxArr(learnPendingPhotos,i)});els.learnUploadPreview.appendChild(d)})}else{els.learnUploadPreview.classList.remove('has-items');els.learnUploadPlaceholder.style.display=''}}
function handleLearnDragOver(e){e.preventDefault();e.stopPropagation();els.learnPhotoZone.classList.add('drag-over')}
function handleLearnDragLeave(e){e.preventDefault();e.stopPropagation();els.learnPhotoZone.classList.remove('drag-over')}
function handleLearnDrop(e){e.preventDefault();e.stopPropagation();els.learnPhotoZone.classList.remove('drag-over');if(e.dataTransfer.files.length)handleLearnPhotoFiles(e.dataTransfer.files)}
function exportLearnCSV(){if(!learns.length){showToast('No learnings to export.');return}var h=['Date','Category','Title','Description','Key Rules'];var rows=learns.sort(function(a,b){return new Date(b.date)-new Date(a.date)}).map(function(l){return[l.date,l.category,l.title,l.description||'',l.rules||'']});var csv=[h].concat(rows).map(function(r){return r.map(function(c){return csvEsc(c)}).join(',')}).join('\n');dlFile(csv,'trade-journal-learnings.csv','text/csv;charset=utf-8;');showToast('Learnings exported.')}

function dlFile(c,n,m){var b=new Blob(['\uFEFF'+c],{type:m});var u=URL.createObjectURL(b);var a=document.createElement('a');a.href=u;a.download=n;document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(u)}

function bindEvents(){
  els.themeToggle.addEventListener('click',toggleTheme);
  $$('.tab-btn').forEach(function(b){b.addEventListener('click',function(){$$('.tab-btn').forEach(function(x){x.classList.remove('active')});b.classList.add('active');$$('.tab-content').forEach(function(x){x.classList.remove('active')});var tabId='tab'+b.getAttribute('data-tab').charAt(0).toUpperCase()+b.getAttribute('data-tab').slice(1);$('#'+tabId).classList.add('active')})});
  els.tradeForm.addEventListener('submit',handleFormSubmit);
  els.cancelEditBtn.addEventListener('click',cancelEdit);
  $$('.btn-group').forEach(function(g){g.querySelectorAll('.seg-btn').forEach(function(b){b.addEventListener('click',function(){g.querySelectorAll('.seg-btn').forEach(function(x){x.classList.remove('active')});b.classList.add('active')})})});
  els.searchInput.addEventListener('input',function(e){searchQuery=e.target.value;renderHistory()});
  els.filterChips.addEventListener('click',function(e){var c=e.target.closest('.chip');if(!c)return;els.filterChips.querySelectorAll('.chip').forEach(function(x){x.classList.remove('active')});c.classList.add('active');currentFilter=c.getAttribute('data-filter');renderHistory()});
  els.exportCsvBtn.addEventListener('click',exportCSV);
  els.exportExcelBtn.addEventListener('click',exportExcel);
  els.importBtn.addEventListener('click',importData);
  els.importFile.addEventListener('change',handleImport);
  els.clearAllBtn.addEventListener('click',promptClearAll);
  els.confirmClearBtn.addEventListener('click',confirmClearAll);
  els.cancelClearBtn.addEventListener('click',closeModals);
  els.confirmDeleteBtn.addEventListener('click',confirmDelete);
  els.cancelDeleteBtn.addEventListener('click',closeModals);
  els.deleteModal.addEventListener('click',function(e){if(e.target===els.deleteModal)closeModals()});
  els.clearModal.addEventListener('click',function(e){if(e.target===els.clearModal)closeModals()});
  els.photoUploadZone.addEventListener('click',handlePhotoClick);
  els.photoInput.addEventListener('change',function(e){if(e.target.files.length){handlePhotoFiles(e.target.files);e.target.value=''}});
  els.photoUploadZone.addEventListener('dragover',handleDragOver);
  els.photoUploadZone.addEventListener('dragleave',handleDragLeave);
  els.photoUploadZone.addEventListener('drop',handleDrop);
  els.lightboxClose.addEventListener('click',closeLightbox);
  els.lightboxPrev.addEventListener('click',lbPrev);
  els.lightboxNext.addEventListener('click',lbNext);
  els.lightboxOverlay.addEventListener('click',function(e){if(e.target===els.lightboxOverlay)closeLightbox()});

  els.addStrategyBtn.addEventListener('click',addNewStrategy);
  $('#closeStrategyModal').addEventListener('click',closeStrategyModal);
  $('#saveStrategyModalBtn').addEventListener('click',saveStrategyModal);
  $('#cancelStrategyModalBtn').addEventListener('click',closeStrategyModal);
  $('#deleteStrategyModalBtn').addEventListener('click',confirmDeleteStrategy);
  els.strategyModal.addEventListener('click',function(e){if(e.target===els.strategyModal)closeStrategyModal()});

  els.learnForm.addEventListener('submit',handleLearnSubmit);
  els.learnCancelBtn.addEventListener('click',cancelLearnEdit);
  els.learnSearchInput.addEventListener('input',function(e){learnSearchQuery=e.target.value;renderLearnCards()});
  els.learnFilterChips.addEventListener('click',function(e){var c=e.target.closest('.chip');if(!c)return;els.learnFilterChips.querySelectorAll('.chip').forEach(function(x){x.classList.remove('active')});c.classList.add('active');learnCurrentFilter=c.getAttribute('data-filter');renderLearnCards()});
  els.exportLearnBtn.addEventListener('click',exportLearnCSV);
  els.clearLearnBtn.addEventListener('click',promptClearLearn);
  els.confirmLearnClearBtn.addEventListener('click',confirmClearLearn);
  els.cancelLearnClearBtn.addEventListener('click',closeModals);
  els.learnDeleteModal.addEventListener('click',function(e){if(e.target===els.learnDeleteModal)closeModals()});
  els.learnClearModal.addEventListener('click',function(e){if(e.target===els.learnClearModal)closeModals()});
  els.confirmLearnDeleteBtn.addEventListener('click',confirmLearnDelete);
  els.cancelLearnDeleteBtn.addEventListener('click',closeModals);
  els.learnPhotoZone.addEventListener('click',handleLearnPhotoClick);
  els.learnPhotoInput.addEventListener('change',function(e){if(e.target.files.length){handleLearnPhotoFiles(e.target.files);e.target.value=''}});
  els.learnPhotoZone.addEventListener('dragover',handleLearnDragOver);
  els.learnPhotoZone.addEventListener('dragleave',handleLearnDragLeave);
  els.learnPhotoZone.addEventListener('drop',handleLearnDrop);

  $('#tradeViewModal').addEventListener('click',function(e){if(e.target===$('#tradeViewModal'))closeTradeView()});
  $('#closeTradeViewModal').addEventListener('click',closeTradeView);
  $('#closeTradeViewBtn').addEventListener('click',closeTradeView);
  $('#tradeViewEditBtn').addEventListener('click',tradeViewEdit);
  $('#learnViewModal').addEventListener('click',function(e){if(e.target===$('#learnViewModal'))closeLearnView()});
  $('#closeLearnViewModal').addEventListener('click',closeLearnView);
  $('#closeLearnViewBtn').addEventListener('click',closeLearnView);
  $('#learnViewEditBtn').addEventListener('click',learnViewEdit);

  document.addEventListener('keydown',function(e){if(e.key==='Escape'){if($('#strategyModal').classList.contains('active'))closeStrategyModal();else if($('#tradeViewModal').classList.contains('active'))closeTradeView();else if($('#learnViewModal').classList.contains('active'))closeLearnView();else if(els.lightboxOverlay.classList.contains('active'))closeLightbox();else closeModals()}if(els.lightboxOverlay.classList.contains('active')){if(e.key==='ArrowLeft')lbPrev();if(e.key==='ArrowRight')lbNext()}});
}

document.addEventListener('DOMContentLoaded',init);
